In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6317, 7489, 4197, 6387],
 [6317, 7489, 4197, 6755],
 [6317, 2267, 4197, 7106],
 [2950, 8323, 7064, 9205, 9890],
 [2950, 8323, 7064, 9205, 2553],
 [4959, 6317, 5514, 4197, 4040],
 [2235, 1688, 5657, 9205]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6317 7489 4197 6387]
 [   0    0    0    0 6317 7489 4197 6755]
 [   0    0    0    0 6317 2267 4197 7106]
 [   0    0    0 2950 8323 7064 9205 9890]
 [   0    0    0 2950 8323 7064 9205 2553]
 [   0    0    0 4959 6317 5514 4197 4040]
 [   0    0    0    0 2235 1688 5657 9205]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Anjaneya workspace\Adv AI ML\venv_py312\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


array([[[ 0.03580293,  0.01598309,  0.04798845,  0.01964455,
         -0.04900823,  0.03935258,  0.04774941, -0.0181318 ,
          0.00207038, -0.03634826],
        [ 0.03580293,  0.01598309,  0.04798845,  0.01964455,
         -0.04900823,  0.03935258,  0.04774941, -0.0181318 ,
          0.00207038, -0.03634826],
        [ 0.03580293,  0.01598309,  0.04798845,  0.01964455,
         -0.04900823,  0.03935258,  0.04774941, -0.0181318 ,
          0.00207038, -0.03634826],
        [ 0.03580293,  0.01598309,  0.04798845,  0.01964455,
         -0.04900823,  0.03935258,  0.04774941, -0.0181318 ,
          0.00207038, -0.03634826],
        [-0.02130208,  0.03133837, -0.01929637, -0.03959037,
          0.04600472,  0.02573862,  0.01991626, -0.00907137,
          0.02660873,  0.03021098],
        [-0.02324514, -0.0118321 ,  0.02843335,  0.03686703,
          0.0253364 ,  0.02184831, -0.0399079 , -0.02125533,
         -0.00706095,  0.03098292],
        [ 0.01251194, -0.03882239, -0.04481139, -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 6317, 7489, 4197, 6387], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [17]:
import numpy as np

# Assuming embedded_docs[0] is a 1D NumPy array
single_sample = embedded_docs[0]

# Reshape the 1D array (n_features,) into a 2D array (1, n_features)
# The '-1' in reshape tells NumPy to automatically calculate the dimension size.
reshaped_sample = single_sample.reshape(1, -1)

# Now, make the prediction
prediction = model.predict(reshaped_sample)

print(prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
[[[ 0.03580293  0.01598309  0.04798845  0.01964455 -0.04900823
    0.03935258  0.04774941 -0.0181318   0.00207038 -0.03634826]
  [ 0.03580293  0.01598309  0.04798845  0.01964455 -0.04900823
    0.03935258  0.04774941 -0.0181318   0.00207038 -0.03634826]
  [ 0.03580293  0.01598309  0.04798845  0.01964455 -0.04900823
    0.03935258  0.04774941 -0.0181318   0.00207038 -0.03634826]
  [ 0.03580293  0.01598309  0.04798845  0.01964455 -0.04900823
    0.03935258  0.04774941 -0.0181318   0.00207038 -0.03634826]
  [-0.02130208  0.03133837 -0.01929637 -0.03959037  0.04600472
    0.02573862  0.01991626 -0.00907137  0.02660873  0.03021098]
  [-0.02324514 -0.0118321   0.02843335  0.03686703  0.0253364
    0.02184831 -0.0399079  -0.02125533 -0.00706095  0.03098292]
  [ 0.01251194 -0.03882239 -0.04481139 -0.00670835  0.04941363
    0.01656537 -0.03461403 -0.00423529  0.04493785 -0.02197393]
  [ 0.00347941  0.02470653 -0.01766573  0.00614771 -0.02545289
    0.01071

In [ ]:
# Pass the sample inside a list to create the "batch" dimension
prediction = model.predict([embedded_docs[0]])

print(prediction)


In [ ]:
import numpy as np

# Assuming embedded_docs[0] is a 1D NumPy array
single_sample = embedded_docs[0]

# Add a new axis at the beginning (axis=0)
reshaped_sample = np.expand_dims(single_sample, axis=0)

# Now, make the prediction
prediction = model.predict(reshaped_sample)

print(prediction)
